export const SET_CAM_POS = 'SET_CAM_POS';
export const SET_ORBIT_CENTER = 'SET_ORBIT_CENTER';
export const SET_SCENE_DIMENSIONS = 'SET_SCENE_DIMENSIONS';
export const ADD_HOVERED_OBJ = 'ADD_HOVERED_OBJ';
export const REM_HOVERED_OBJ = 'REM_HOVERED_OBJ';
export const TOGGLE_BUTTON_PRESS = 'TOGGLE_BUTTON_PRESS';
